### PR TITLE
write article on pytorch static quantization

### LINKED ISSUE #13: `blog`: Demystify torch quantization

### PR DESCRIPTION
**Pull request by harukadoyu**
Closes #13

### CODE REVIEW

**Comment by harukadoyu** [comment]
Fixes #13

**Review by harukadoyu — COMMENTED** [review]
testing

**Comment by harukadoyu** [comment]
The issue in KB hasn't moved to `PR to review`. What should I do?

**Comment by harukadoyu** [comment]
IIUC, the issue moves to `PR to review` after requesting changes in PR, not when sending PR.

**Comment by doyu** [comment]
> IIUC, the issue moves to `PR to review` after requesting changes in PR, not when sending PR.

Right :(

**Review by doyu — APPROVED** [review]

**Pull request merged**
